// @generated by protobuf-ts 2.11.0 with parameter generate_dependencies,long_type_string
// @generated from protobuf file "chunksink.proto" (package "chunksink", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChunkSink } from "./chunksink";
import type { Command } from "./chunksink";
import type { GetCommandRequest } from "./chunksink";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { Chunks } from "./chunksink";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Respone } from "./common";
import type { RecorderStatus } from "./common";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chunksink.ChunkSink
 */
export interface IChunkSinkClient {
    /**
     * Unary
     *
     * @generated from protobuf rpc: SetRecorderStatus
     */
    setRecorderStatus(input: RecorderStatus, options?: RpcOptions): UnaryCall<RecorderStatus, Respone>;
    /**
     * @generated from protobuf rpc: SetChunks
     */
    setChunks(input: Chunks, options?: RpcOptions): UnaryCall<Chunks, Respone>;
    /**
     * Server streaming
     *
     * @generated from protobuf rpc: GetCommands
     */
    getCommands(input: GetCommandRequest, options?: RpcOptions): ServerStreamingCall<GetCommandRequest, Command>;
}
/**
 * @generated from protobuf service chunksink.ChunkSink
 */
export class ChunkSinkClient implements IChunkSinkClient, ServiceInfo {
    typeName = ChunkSink.typeName;
    methods = ChunkSink.methods;
    options = ChunkSink.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Unary
     *
     * @generated from protobuf rpc: SetRecorderStatus
     */
    setRecorderStatus(input: RecorderStatus, options?: RpcOptions): UnaryCall<RecorderStatus, Respone> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RecorderStatus, Respone>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetChunks
     */
    setChunks(input: Chunks, options?: RpcOptions): UnaryCall<Chunks, Respone> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Chunks, Respone>("unary", this._transport, method, opt, input);
    }
    /**
     * Server streaming
     *
     * @generated from protobuf rpc: GetCommands
     */
    getCommands(input: GetCommandRequest, options?: RpcOptions): ServerStreamingCall<GetCommandRequest, Command> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCommandRequest, Command>("serverStreaming", this._transport, method, opt, input);
    }
}
