// source: sessionsource.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sessionsource.OpenSessions', null, global);
goog.exportSymbol('proto.sessionsource.Session', null, global);
goog.exportSymbol('proto.sessionsource.StreamOpenSessionsRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sessionsource.StreamOpenSessionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sessionsource.StreamOpenSessionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sessionsource.StreamOpenSessionsRequest.displayName = 'proto.sessionsource.StreamOpenSessionsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sessionsource.OpenSessions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sessionsource.OpenSessions.repeatedFields_, null);
};
goog.inherits(proto.sessionsource.OpenSessions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sessionsource.OpenSessions.displayName = 'proto.sessionsource.OpenSessions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sessionsource.Session = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sessionsource.Session.repeatedFields_, null);
};
goog.inherits(proto.sessionsource.Session, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sessionsource.Session.displayName = 'proto.sessionsource.Session';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sessionsource.StreamOpenSessionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.sessionsource.StreamOpenSessionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sessionsource.StreamOpenSessionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.StreamOpenSessionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sessionsource.StreamOpenSessionsRequest}
 */
proto.sessionsource.StreamOpenSessionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sessionsource.StreamOpenSessionsRequest;
  return proto.sessionsource.StreamOpenSessionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sessionsource.StreamOpenSessionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sessionsource.StreamOpenSessionsRequest}
 */
proto.sessionsource.StreamOpenSessionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sessionsource.StreamOpenSessionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sessionsource.StreamOpenSessionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sessionsource.StreamOpenSessionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.StreamOpenSessionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sessionsource.OpenSessions.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sessionsource.OpenSessions.prototype.toObject = function(opt_includeInstance) {
  return proto.sessionsource.OpenSessions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sessionsource.OpenSessions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.OpenSessions.toObject = function(includeInstance, msg) {
  var f, obj = {
    opensessionsList: jspb.Message.toObjectList(msg.getOpensessionsList(),
    proto.sessionsource.Session.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sessionsource.OpenSessions}
 */
proto.sessionsource.OpenSessions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sessionsource.OpenSessions;
  return proto.sessionsource.OpenSessions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sessionsource.OpenSessions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sessionsource.OpenSessions}
 */
proto.sessionsource.OpenSessions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sessionsource.Session;
      reader.readMessage(value,proto.sessionsource.Session.deserializeBinaryFromReader);
      msg.addOpensessions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sessionsource.OpenSessions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sessionsource.OpenSessions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sessionsource.OpenSessions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.OpenSessions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpensessionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.sessionsource.Session.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Session openSessions = 1;
 * @return {!Array<!proto.sessionsource.Session>}
 */
proto.sessionsource.OpenSessions.prototype.getOpensessionsList = function() {
  return /** @type{!Array<!proto.sessionsource.Session>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sessionsource.Session, 1));
};


/**
 * @param {!Array<!proto.sessionsource.Session>} value
 * @return {!proto.sessionsource.OpenSessions} returns this
*/
proto.sessionsource.OpenSessions.prototype.setOpensessionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.sessionsource.Session=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sessionsource.Session}
 */
proto.sessionsource.OpenSessions.prototype.addOpensessions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.sessionsource.Session, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sessionsource.OpenSessions} returns this
 */
proto.sessionsource.OpenSessions.prototype.clearOpensessionsList = function() {
  return this.setOpensessionsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sessionsource.Session.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sessionsource.Session.prototype.toObject = function(opt_includeInstance) {
  return proto.sessionsource.Session.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sessionsource.Session} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.Session.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    audiofilenamesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    waveformdatafile: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timecreated: jspb.Message.getFieldWithDefault(msg, 4, 0),
    length: jspb.Message.getFieldWithDefault(msg, 5, 0),
    livetimehours: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    keepsession: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sessionsource.Session}
 */
proto.sessionsource.Session.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sessionsource.Session;
  return proto.sessionsource.Session.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sessionsource.Session} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sessionsource.Session}
 */
proto.sessionsource.Session.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAudiofilenames(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWaveformdatafile(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimecreated(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLength(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLivetimehours(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setKeepsession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sessionsource.Session.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sessionsource.Session.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sessionsource.Session} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sessionsource.Session.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAudiofilenamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getWaveformdatafile();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimecreated();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getLivetimehours();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getKeepsession();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string ID = 1;
 * @return {string}
 */
proto.sessionsource.Session.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string audioFileNames = 2;
 * @return {!Array<string>}
 */
proto.sessionsource.Session.prototype.getAudiofilenamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setAudiofilenamesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.addAudiofilenames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.clearAudiofilenamesList = function() {
  return this.setAudiofilenamesList([]);
};


/**
 * optional string waveformDataFile = 3;
 * @return {string}
 */
proto.sessionsource.Session.prototype.getWaveformdatafile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setWaveformdatafile = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 timeCreated = 4;
 * @return {number}
 */
proto.sessionsource.Session.prototype.getTimecreated = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setTimecreated = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 length = 5;
 * @return {number}
 */
proto.sessionsource.Session.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setLength = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional float livetimeHours = 6;
 * @return {number}
 */
proto.sessionsource.Session.prototype.getLivetimehours = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setLivetimehours = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional bool keepSession = 7;
 * @return {boolean}
 */
proto.sessionsource.Session.prototype.getKeepsession = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sessionsource.Session} returns this
 */
proto.sessionsource.Session.prototype.setKeepsession = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


goog.object.extend(exports, proto.sessionsource);
