// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalStatus int32

const (
	SignalStatus_UNKNOWN   SignalStatus = 0
	SignalStatus_NO_SIGNAL SignalStatus = 1
	SignalStatus_SIGNAL    SignalStatus = 2
)

// Enum value maps for SignalStatus.
var (
	SignalStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO_SIGNAL",
		2: "SIGNAL",
	}
	SignalStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"NO_SIGNAL": 1,
		"SIGNAL":    2,
	}
)

func (x SignalStatus) Enum() *SignalStatus {
	p := new(SignalStatus)
	*p = x
	return p
}

func (x SignalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (SignalStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x SignalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalStatus.Descriptor instead.
func (SignalStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type RecorderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	RecorderName  string                 `protobuf:"bytes,2,opt,name=recorderName,proto3" json:"recorderName,omitempty"`
	SignalStatus  SignalStatus           `protobuf:"varint,3,opt,name=signalStatus,proto3,enum=common.SignalStatus" json:"signalStatus,omitempty"`
	RmsPercent    float64                `protobuf:"fixed64,4,opt,name=rmsPercent,proto3" json:"rmsPercent,omitempty"`
	Clipping      bool                   `protobuf:"varint,5,opt,name=clipping,proto3" json:"clipping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecorderStatus) Reset() {
	*x = RecorderStatus{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecorderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecorderStatus) ProtoMessage() {}

func (x *RecorderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecorderStatus.ProtoReflect.Descriptor instead.
func (*RecorderStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *RecorderStatus) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *RecorderStatus) GetRecorderName() string {
	if x != nil {
		return x.RecorderName
	}
	return ""
}

func (x *RecorderStatus) GetSignalStatus() SignalStatus {
	if x != nil {
		return x.SignalStatus
	}
	return SignalStatus_UNKNOWN
}

func (x *RecorderStatus) GetRmsPercent() float64 {
	if x != nil {
		return x.RmsPercent
	}
	return 0
}

func (x *RecorderStatus) GetClipping() bool {
	if x != nil {
		return x.Clipping
	}
	return false
}

type Respone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respone) Reset() {
	*x = Respone{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respone) ProtoMessage() {}

func (x *Respone) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respone.ProtoReflect.Descriptor instead.
func (*Respone) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Respone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Respone) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"\xca\x01\n" +
	"\x0eRecorderStatus\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\"\n" +
	"\frecorderName\x18\x02 \x01(\tR\frecorderName\x128\n" +
	"\fsignalStatus\x18\x03 \x01(\x0e2\x14.common.SignalStatusR\fsignalStatus\x12\x1e\n" +
	"\n" +
	"rmsPercent\x18\x04 \x01(\x01R\n" +
	"rmsPercent\x12\x1a\n" +
	"\bclipping\x18\x05 \x01(\bR\bclipping\"G\n" +
	"\aRespone\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage*6\n" +
	"\fSignalStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tNO_SIGNAL\x10\x01\x12\n" +
	"\n" +
	"\x06SIGNAL\x10\x02B>Z<github.com/pascalhuerst/session-recorder/protocols/go/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(SignalStatus)(0),      // 0: common.SignalStatus
	(*RecorderStatus)(nil), // 1: common.RecorderStatus
	(*Respone)(nil),        // 2: common.Respone
}
var file_common_proto_depIdxs = []int32{
	0, // 0: common.RecorderStatus.signalStatus:type_name -> common.SignalStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
