// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chunksink

import (
	context "context"
	common "github.com/pascalhuerst/session-recorder/protocols/go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChunkSinkClient is the client API for ChunkSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkSinkClient interface {
	// Unary
	SetRecorderStatus(ctx context.Context, in *common.RecorderStatus, opts ...grpc.CallOption) (*common.Respone, error)
	SetChunks(ctx context.Context, in *Chunks, opts ...grpc.CallOption) (*common.Respone, error)
	// Server streaming
	GetCommands(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (ChunkSink_GetCommandsClient, error)
}

type chunkSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkSinkClient(cc grpc.ClientConnInterface) ChunkSinkClient {
	return &chunkSinkClient{cc}
}

func (c *chunkSinkClient) SetRecorderStatus(ctx context.Context, in *common.RecorderStatus, opts ...grpc.CallOption) (*common.Respone, error) {
	out := new(common.Respone)
	err := c.cc.Invoke(ctx, "/chunksink.ChunkSink/SetRecorderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkSinkClient) SetChunks(ctx context.Context, in *Chunks, opts ...grpc.CallOption) (*common.Respone, error) {
	out := new(common.Respone)
	err := c.cc.Invoke(ctx, "/chunksink.ChunkSink/SetChunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkSinkClient) GetCommands(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (ChunkSink_GetCommandsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChunkSink_ServiceDesc.Streams[0], "/chunksink.ChunkSink/GetCommands", opts...)
	if err != nil {
		return nil, err
	}
	x := &chunkSinkGetCommandsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChunkSink_GetCommandsClient interface {
	Recv() (*Command, error)
	grpc.ClientStream
}

type chunkSinkGetCommandsClient struct {
	grpc.ClientStream
}

func (x *chunkSinkGetCommandsClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChunkSinkServer is the server API for ChunkSink service.
// All implementations should embed UnimplementedChunkSinkServer
// for forward compatibility
type ChunkSinkServer interface {
	// Unary
	SetRecorderStatus(context.Context, *common.RecorderStatus) (*common.Respone, error)
	SetChunks(context.Context, *Chunks) (*common.Respone, error)
	// Server streaming
	GetCommands(*GetCommandRequest, ChunkSink_GetCommandsServer) error
}

// UnimplementedChunkSinkServer should be embedded to have forward compatible implementations.
type UnimplementedChunkSinkServer struct {
}

func (UnimplementedChunkSinkServer) SetRecorderStatus(context.Context, *common.RecorderStatus) (*common.Respone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRecorderStatus not implemented")
}
func (UnimplementedChunkSinkServer) SetChunks(context.Context, *Chunks) (*common.Respone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetChunks not implemented")
}
func (UnimplementedChunkSinkServer) GetCommands(*GetCommandRequest, ChunkSink_GetCommandsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCommands not implemented")
}

// UnsafeChunkSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkSinkServer will
// result in compilation errors.
type UnsafeChunkSinkServer interface {
	mustEmbedUnimplementedChunkSinkServer()
}

func RegisterChunkSinkServer(s grpc.ServiceRegistrar, srv ChunkSinkServer) {
	s.RegisterService(&ChunkSink_ServiceDesc, srv)
}

func _ChunkSink_SetRecorderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.RecorderStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkSinkServer).SetRecorderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chunksink.ChunkSink/SetRecorderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkSinkServer).SetRecorderStatus(ctx, req.(*common.RecorderStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkSink_SetChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkSinkServer).SetChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chunksink.ChunkSink/SetChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkSinkServer).SetChunks(ctx, req.(*Chunks))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkSink_GetCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkSinkServer).GetCommands(m, &chunkSinkGetCommandsServer{stream})
}

type ChunkSink_GetCommandsServer interface {
	Send(*Command) error
	grpc.ServerStream
}

type chunkSinkGetCommandsServer struct {
	grpc.ServerStream
}

func (x *chunkSinkGetCommandsServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

// ChunkSink_ServiceDesc is the grpc.ServiceDesc for ChunkSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chunksink.ChunkSink",
	HandlerType: (*ChunkSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRecorderStatus",
			Handler:    _ChunkSink_SetRecorderStatus_Handler,
		},
		{
			MethodName: "SetChunks",
			Handler:    _ChunkSink_SetChunks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCommands",
			Handler:       _ChunkSink_GetCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chunksink.proto",
}
