// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: chunksink.proto

package chunksink

import (
	common "github.com/pascalhuerst/session-recorder/protocols/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,3,opt,name=chunkCount,proto3" json:"chunkCount,omitempty"`
	TimeCreated   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timeCreated,proto3" json:"timeCreated,omitempty"`
	Data          []uint32               `protobuf:"varint,5,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunks) Reset() {
	*x = Chunks{}
	mi := &file_chunksink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunks) ProtoMessage() {}

func (x *Chunks) ProtoReflect() protoreflect.Message {
	mi := &file_chunksink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunks.ProtoReflect.Descriptor instead.
func (*Chunks) Descriptor() ([]byte, []int) {
	return file_chunksink_proto_rawDescGZIP(), []int{0}
}

func (x *Chunks) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *Chunks) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Chunks) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Chunks) GetTimeCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

func (x *Chunks) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequest) Reset() {
	*x = GetCommandRequest{}
	mi := &file_chunksink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequest) ProtoMessage() {}

func (x *GetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chunksink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequest) Descriptor() ([]byte, []int) {
	return file_chunksink_proto_rawDescGZIP(), []int{1}
}

func (x *GetCommandRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

type CmdCutSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCutSession) Reset() {
	*x = CmdCutSession{}
	mi := &file_chunksink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCutSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCutSession) ProtoMessage() {}

func (x *CmdCutSession) ProtoReflect() protoreflect.Message {
	mi := &file_chunksink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCutSession.ProtoReflect.Descriptor instead.
func (*CmdCutSession) Descriptor() ([]byte, []int) {
	return file_chunksink_proto_rawDescGZIP(), []int{2}
}

type Reboot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reboot) Reset() {
	*x = Reboot{}
	mi := &file_chunksink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reboot) ProtoMessage() {}

func (x *Reboot) ProtoReflect() protoreflect.Message {
	mi := &file_chunksink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reboot.ProtoReflect.Descriptor instead.
func (*Reboot) Descriptor() ([]byte, []int) {
	return file_chunksink_proto_rawDescGZIP(), []int{3}
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*Command_Reboot
	//	*Command_CmdCutSession
	Command       isCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_chunksink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_chunksink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_chunksink_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommand() isCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Command) GetReboot() *Reboot {
	if x != nil {
		if x, ok := x.Command.(*Command_Reboot); ok {
			return x.Reboot
		}
	}
	return nil
}

func (x *Command) GetCmdCutSession() *CmdCutSession {
	if x != nil {
		if x, ok := x.Command.(*Command_CmdCutSession); ok {
			return x.CmdCutSession
		}
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_Reboot struct {
	Reboot *Reboot `protobuf:"bytes,1,opt,name=reboot,proto3,oneof"`
}

type Command_CmdCutSession struct {
	CmdCutSession *CmdCutSession `protobuf:"bytes,2,opt,name=cmdCutSession,proto3,oneof"`
}

func (*Command_Reboot) isCommand_Command() {}

func (*Command_CmdCutSession) isCommand_Command() {}

var File_chunksink_proto protoreflect.FileDescriptor

const file_chunksink_proto_rawDesc = "" +
	"\n" +
	"\x0fchunksink.proto\x12\tchunksink\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\x06Chunks\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1e\n" +
	"\n" +
	"chunkCount\x18\x03 \x01(\rR\n" +
	"chunkCount\x12<\n" +
	"\vtimeCreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeCreated\x12\x12\n" +
	"\x04data\x18\x05 \x03(\rR\x04data\"3\n" +
	"\x11GetCommandRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\"\x0f\n" +
	"\rCmdCutSession\"\b\n" +
	"\x06Reboot\"\x83\x01\n" +
	"\aCommand\x12+\n" +
	"\x06reboot\x18\x01 \x01(\v2\x11.chunksink.RebootH\x00R\x06reboot\x12@\n" +
	"\rcmdCutSession\x18\x02 \x01(\v2\x18.chunksink.CmdCutSessionH\x00R\rcmdCutSessionB\t\n" +
	"\acommand2\xbd\x01\n" +
	"\tChunkSink\x12<\n" +
	"\x11SetRecorderStatus\x12\x16.common.RecorderStatus\x1a\x0f.common.Respone\x12/\n" +
	"\tSetChunks\x12\x11.chunksink.Chunks\x1a\x0f.common.Respone\x12A\n" +
	"\vGetCommands\x12\x1c.chunksink.GetCommandRequest\x1a\x12.chunksink.Command0\x01BAZ?github.com/pascalhuerst/session-recorder/protocols/go/chunksinkb\x06proto3"

var (
	file_chunksink_proto_rawDescOnce sync.Once
	file_chunksink_proto_rawDescData []byte
)

func file_chunksink_proto_rawDescGZIP() []byte {
	file_chunksink_proto_rawDescOnce.Do(func() {
		file_chunksink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chunksink_proto_rawDesc), len(file_chunksink_proto_rawDesc)))
	})
	return file_chunksink_proto_rawDescData
}

var file_chunksink_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chunksink_proto_goTypes = []any{
	(*Chunks)(nil),                // 0: chunksink.Chunks
	(*GetCommandRequest)(nil),     // 1: chunksink.GetCommandRequest
	(*CmdCutSession)(nil),         // 2: chunksink.CmdCutSession
	(*Reboot)(nil),                // 3: chunksink.Reboot
	(*Command)(nil),               // 4: chunksink.Command
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*common.RecorderStatus)(nil), // 6: common.RecorderStatus
	(*common.Respone)(nil),        // 7: common.Respone
}
var file_chunksink_proto_depIdxs = []int32{
	5, // 0: chunksink.Chunks.timeCreated:type_name -> google.protobuf.Timestamp
	3, // 1: chunksink.Command.reboot:type_name -> chunksink.Reboot
	2, // 2: chunksink.Command.cmdCutSession:type_name -> chunksink.CmdCutSession
	6, // 3: chunksink.ChunkSink.SetRecorderStatus:input_type -> common.RecorderStatus
	0, // 4: chunksink.ChunkSink.SetChunks:input_type -> chunksink.Chunks
	1, // 5: chunksink.ChunkSink.GetCommands:input_type -> chunksink.GetCommandRequest
	7, // 6: chunksink.ChunkSink.SetRecorderStatus:output_type -> common.Respone
	7, // 7: chunksink.ChunkSink.SetChunks:output_type -> common.Respone
	4, // 8: chunksink.ChunkSink.GetCommands:output_type -> chunksink.Command
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chunksink_proto_init() }
func file_chunksink_proto_init() {
	if File_chunksink_proto != nil {
		return
	}
	file_chunksink_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_Reboot)(nil),
		(*Command_CmdCutSession)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chunksink_proto_rawDesc), len(file_chunksink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chunksink_proto_goTypes,
		DependencyIndexes: file_chunksink_proto_depIdxs,
		MessageInfos:      file_chunksink_proto_msgTypes,
	}.Build()
	File_chunksink_proto = out.File
	file_chunksink_proto_goTypes = nil
	file_chunksink_proto_depIdxs = nil
}
