// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: chunksink.proto

package chunksink

import (
	context "context"
	common "github.com/pascalhuerst/session-recorder/protocols/go/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkSink_SetRecorderStatus_FullMethodName = "/chunksink.ChunkSink/SetRecorderStatus"
	ChunkSink_SetChunks_FullMethodName         = "/chunksink.ChunkSink/SetChunks"
	ChunkSink_GetCommands_FullMethodName       = "/chunksink.ChunkSink/GetCommands"
)

// ChunkSinkClient is the client API for ChunkSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkSinkClient interface {
	// Unary
	SetRecorderStatus(ctx context.Context, in *common.RecorderStatus, opts ...grpc.CallOption) (*common.Respone, error)
	SetChunks(ctx context.Context, in *Chunks, opts ...grpc.CallOption) (*common.Respone, error)
	// Server streaming
	GetCommands(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
}

type chunkSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkSinkClient(cc grpc.ClientConnInterface) ChunkSinkClient {
	return &chunkSinkClient{cc}
}

func (c *chunkSinkClient) SetRecorderStatus(ctx context.Context, in *common.RecorderStatus, opts ...grpc.CallOption) (*common.Respone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Respone)
	err := c.cc.Invoke(ctx, ChunkSink_SetRecorderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkSinkClient) SetChunks(ctx context.Context, in *Chunks, opts ...grpc.CallOption) (*common.Respone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Respone)
	err := c.cc.Invoke(ctx, ChunkSink_SetChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkSinkClient) GetCommands(ctx context.Context, in *GetCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkSink_ServiceDesc.Streams[0], ChunkSink_GetCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetCommandRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkSink_GetCommandsClient = grpc.ServerStreamingClient[Command]

// ChunkSinkServer is the server API for ChunkSink service.
// All implementations should embed UnimplementedChunkSinkServer
// for forward compatibility.
type ChunkSinkServer interface {
	// Unary
	SetRecorderStatus(context.Context, *common.RecorderStatus) (*common.Respone, error)
	SetChunks(context.Context, *Chunks) (*common.Respone, error)
	// Server streaming
	GetCommands(*GetCommandRequest, grpc.ServerStreamingServer[Command]) error
}

// UnimplementedChunkSinkServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkSinkServer struct{}

func (UnimplementedChunkSinkServer) SetRecorderStatus(context.Context, *common.RecorderStatus) (*common.Respone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRecorderStatus not implemented")
}
func (UnimplementedChunkSinkServer) SetChunks(context.Context, *Chunks) (*common.Respone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetChunks not implemented")
}
func (UnimplementedChunkSinkServer) GetCommands(*GetCommandRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Errorf(codes.Unimplemented, "method GetCommands not implemented")
}
func (UnimplementedChunkSinkServer) testEmbeddedByValue() {}

// UnsafeChunkSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkSinkServer will
// result in compilation errors.
type UnsafeChunkSinkServer interface {
	mustEmbedUnimplementedChunkSinkServer()
}

func RegisterChunkSinkServer(s grpc.ServiceRegistrar, srv ChunkSinkServer) {
	// If the following call pancis, it indicates UnimplementedChunkSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkSink_ServiceDesc, srv)
}

func _ChunkSink_SetRecorderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.RecorderStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkSinkServer).SetRecorderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkSink_SetRecorderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkSinkServer).SetRecorderStatus(ctx, req.(*common.RecorderStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkSink_SetChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkSinkServer).SetChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkSink_SetChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkSinkServer).SetChunks(ctx, req.(*Chunks))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkSink_GetCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkSinkServer).GetCommands(m, &grpc.GenericServerStream[GetCommandRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkSink_GetCommandsServer = grpc.ServerStreamingServer[Command]

// ChunkSink_ServiceDesc is the grpc.ServiceDesc for ChunkSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chunksink.ChunkSink",
	HandlerType: (*ChunkSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRecorderStatus",
			Handler:    _ChunkSink_SetRecorderStatus_Handler,
		},
		{
			MethodName: "SetChunks",
			Handler:    _ChunkSink_SetChunks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCommands",
			Handler:       _ChunkSink_GetCommands_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chunksink.proto",
}
