// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: sessionsource.proto

package sessionsource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SessionSource_HealthCheck_FullMethodName     = "/sessionsource.SessionSource/HealthCheck"
	SessionSource_StreamRecorders_FullMethodName = "/sessionsource.SessionSource/StreamRecorders"
	SessionSource_StreamSessions_FullMethodName  = "/sessionsource.SessionSource/StreamSessions"
)

// SessionSourceClient is the client API for SessionSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionSourceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	StreamRecorders(ctx context.Context, in *StreamRecordersRequest, opts ...grpc.CallOption) (SessionSource_StreamRecordersClient, error)
	StreamSessions(ctx context.Context, in *StreamSeesionRequst, opts ...grpc.CallOption) (SessionSource_StreamSessionsClient, error)
}

type sessionSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionSourceClient(cc grpc.ClientConnInterface) SessionSourceClient {
	return &sessionSourceClient{cc}
}

func (c *sessionSourceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SessionSource_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionSourceClient) StreamRecorders(ctx context.Context, in *StreamRecordersRequest, opts ...grpc.CallOption) (SessionSource_StreamRecordersClient, error) {
	stream, err := c.cc.NewStream(ctx, &SessionSource_ServiceDesc.Streams[0], SessionSource_StreamRecorders_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionSourceStreamRecordersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SessionSource_StreamRecordersClient interface {
	Recv() (*RecorderInfo, error)
	grpc.ClientStream
}

type sessionSourceStreamRecordersClient struct {
	grpc.ClientStream
}

func (x *sessionSourceStreamRecordersClient) Recv() (*RecorderInfo, error) {
	m := new(RecorderInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionSourceClient) StreamSessions(ctx context.Context, in *StreamSeesionRequst, opts ...grpc.CallOption) (SessionSource_StreamSessionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SessionSource_ServiceDesc.Streams[1], SessionSource_StreamSessions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionSourceStreamSessionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SessionSource_StreamSessionsClient interface {
	Recv() (*SessionInfo, error)
	grpc.ClientStream
}

type sessionSourceStreamSessionsClient struct {
	grpc.ClientStream
}

func (x *sessionSourceStreamSessionsClient) Recv() (*SessionInfo, error) {
	m := new(SessionInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SessionSourceServer is the server API for SessionSource service.
// All implementations should embed UnimplementedSessionSourceServer
// for forward compatibility
type SessionSourceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	StreamRecorders(*StreamRecordersRequest, SessionSource_StreamRecordersServer) error
	StreamSessions(*StreamSeesionRequst, SessionSource_StreamSessionsServer) error
}

// UnimplementedSessionSourceServer should be embedded to have forward compatible implementations.
type UnimplementedSessionSourceServer struct {
}

func (UnimplementedSessionSourceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSessionSourceServer) StreamRecorders(*StreamRecordersRequest, SessionSource_StreamRecordersServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRecorders not implemented")
}
func (UnimplementedSessionSourceServer) StreamSessions(*StreamSeesionRequst, SessionSource_StreamSessionsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSessions not implemented")
}

// UnsafeSessionSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionSourceServer will
// result in compilation errors.
type UnsafeSessionSourceServer interface {
	mustEmbedUnimplementedSessionSourceServer()
}

func RegisterSessionSourceServer(s grpc.ServiceRegistrar, srv SessionSourceServer) {
	s.RegisterService(&SessionSource_ServiceDesc, srv)
}

func _SessionSource_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionSourceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionSource_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionSourceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionSource_StreamRecorders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRecordersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionSourceServer).StreamRecorders(m, &sessionSourceStreamRecordersServer{stream})
}

type SessionSource_StreamRecordersServer interface {
	Send(*RecorderInfo) error
	grpc.ServerStream
}

type sessionSourceStreamRecordersServer struct {
	grpc.ServerStream
}

func (x *sessionSourceStreamRecordersServer) Send(m *RecorderInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _SessionSource_StreamSessions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSeesionRequst)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionSourceServer).StreamSessions(m, &sessionSourceStreamSessionsServer{stream})
}

type SessionSource_StreamSessionsServer interface {
	Send(*SessionInfo) error
	grpc.ServerStream
}

type sessionSourceStreamSessionsServer struct {
	grpc.ServerStream
}

func (x *sessionSourceStreamSessionsServer) Send(m *SessionInfo) error {
	return x.ServerStream.SendMsg(m)
}

// SessionSource_ServiceDesc is the grpc.ServiceDesc for SessionSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sessionsource.SessionSource",
	HandlerType: (*SessionSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _SessionSource_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRecorders",
			Handler:       _SessionSource_StreamRecorders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSessions",
			Handler:       _SessionSource_StreamSessions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sessionsource.proto",
}
