// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: sessionsource.proto

package sessionsource

import (
	common "github.com/pascalhuerst/session-recorder/protocols/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentState int32

const (
	SegmentState_SEGMENT_STATE_UNKNOWN   SegmentState = 0
	SegmentState_SEGMENT_STATE_RENDERING SegmentState = 1
	SegmentState_SEGMENT_STATE_FINISHED  SegmentState = 2
	SegmentState_SEGMENT_STATE_ERROR     SegmentState = 3
	SegmentState_SEGMENT_STATE_QUEUED    SegmentState = 4
)

// Enum value maps for SegmentState.
var (
	SegmentState_name = map[int32]string{
		0: "SEGMENT_STATE_UNKNOWN",
		1: "SEGMENT_STATE_RENDERING",
		2: "SEGMENT_STATE_FINISHED",
		3: "SEGMENT_STATE_ERROR",
		4: "SEGMENT_STATE_QUEUED",
	}
	SegmentState_value = map[string]int32{
		"SEGMENT_STATE_UNKNOWN":   0,
		"SEGMENT_STATE_RENDERING": 1,
		"SEGMENT_STATE_FINISHED":  2,
		"SEGMENT_STATE_ERROR":     3,
		"SEGMENT_STATE_QUEUED":    4,
	}
)

func (x SegmentState) Enum() *SegmentState {
	p := new(SegmentState)
	*p = x
	return p
}

func (x SegmentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentState) Descriptor() protoreflect.EnumDescriptor {
	return file_sessionsource_proto_enumTypes[0].Descriptor()
}

func (SegmentState) Type() protoreflect.EnumType {
	return &file_sessionsource_proto_enumTypes[0]
}

func (x SegmentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentState.Descriptor instead.
func (SegmentState) EnumDescriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{0}
}

type SessionState int32

const (
	SessionState_SESSION_STATE_UNKNOWN    SessionState = 0
	SessionState_SESSION_STATE_RECORDING  SessionState = 1
	SessionState_SESSION_STATE_FINISHED   SessionState = 2
	SessionState_SESSION_STATE_PROCESSING SessionState = 3
	SessionState_SESSION_STATE_ERROR      SessionState = 4
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNKNOWN",
		1: "SESSION_STATE_RECORDING",
		2: "SESSION_STATE_FINISHED",
		3: "SESSION_STATE_PROCESSING",
		4: "SESSION_STATE_ERROR",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNKNOWN":    0,
		"SESSION_STATE_RECORDING":  1,
		"SESSION_STATE_FINISHED":   2,
		"SESSION_STATE_PROCESSING": 3,
		"SESSION_STATE_ERROR":      4,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_sessionsource_proto_enumTypes[1].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_sessionsource_proto_enumTypes[1]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{1}
}

type StreamRecordersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRecordersRequest) Reset() {
	*x = StreamRecordersRequest{}
	mi := &file_sessionsource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRecordersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRecordersRequest) ProtoMessage() {}

func (x *StreamRecordersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRecordersRequest.ProtoReflect.Descriptor instead.
func (*StreamRecordersRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{0}
}

type RecordereRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordereRemoved) Reset() {
	*x = RecordereRemoved{}
	mi := &file_sessionsource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordereRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordereRemoved) ProtoMessage() {}

func (x *RecordereRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordereRemoved.ProtoReflect.Descriptor instead.
func (*RecordereRemoved) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{1}
}

type Recorder struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RecorderID   string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	RecorderName string                 `protobuf:"bytes,2,opt,name=recorderName,proto3" json:"recorderName,omitempty"`
	// Types that are valid to be assigned to Info:
	//
	//	*Recorder_Status
	//	*Recorder_Removed
	Info          isRecorder_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recorder) Reset() {
	*x = Recorder{}
	mi := &file_sessionsource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recorder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recorder) ProtoMessage() {}

func (x *Recorder) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recorder.ProtoReflect.Descriptor instead.
func (*Recorder) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{2}
}

func (x *Recorder) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *Recorder) GetRecorderName() string {
	if x != nil {
		return x.RecorderName
	}
	return ""
}

func (x *Recorder) GetInfo() isRecorder_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Recorder) GetStatus() *common.RecorderStatus {
	if x != nil {
		if x, ok := x.Info.(*Recorder_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Recorder) GetRemoved() *RecordereRemoved {
	if x != nil {
		if x, ok := x.Info.(*Recorder_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

type isRecorder_Info interface {
	isRecorder_Info()
}

type Recorder_Status struct {
	Status *common.RecorderStatus `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type Recorder_Removed struct {
	Removed *RecordereRemoved `protobuf:"bytes,4,opt,name=removed,proto3,oneof"`
}

func (*Recorder_Status) isRecorder_Info() {}

func (*Recorder_Removed) isRecorder_Info() {}

type StreamSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSessionRequest) Reset() {
	*x = StreamSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSessionRequest) ProtoMessage() {}

func (x *StreamSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSessionRequest.ProtoReflect.Descriptor instead.
func (*StreamSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{3}
}

func (x *StreamSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStart     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State         SegmentState           `protobuf:"varint,4,opt,name=state,proto3,enum=sessionsource.SegmentState" json:"state,omitempty"`
	InlineFiles   *SegmentInfo_Files     `protobuf:"bytes,5,opt,name=inlineFiles,proto3" json:"inlineFiles,omitempty"`
	DownloadFiles *SegmentInfo_Files     `protobuf:"bytes,6,opt,name=downloadFiles,proto3" json:"downloadFiles,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_sessionsource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentInfo) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *SegmentInfo) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *SegmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SegmentInfo) GetState() SegmentState {
	if x != nil {
		return x.State
	}
	return SegmentState_SEGMENT_STATE_UNKNOWN
}

func (x *SegmentInfo) GetInlineFiles() *SegmentInfo_Files {
	if x != nil {
		return x.InlineFiles
	}
	return nil
}

func (x *SegmentInfo) GetDownloadFiles() *SegmentInfo_Files {
	if x != nil {
		return x.DownloadFiles
	}
	return nil
}

func (x *SegmentInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SegmentRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentRemoved) Reset() {
	*x = SegmentRemoved{}
	mi := &file_sessionsource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRemoved) ProtoMessage() {}

func (x *SegmentRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRemoved.ProtoReflect.Descriptor instead.
func (*SegmentRemoved) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{5}
}

type Segment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentID string                 `protobuf:"bytes,1,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	// Types that are valid to be assigned to Info:
	//
	//	*Segment_Updated
	//	*Segment_Removed
	Info          isSegment_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_sessionsource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{6}
}

func (x *Segment) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

func (x *Segment) GetInfo() isSegment_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Segment) GetUpdated() *SegmentInfo {
	if x != nil {
		if x, ok := x.Info.(*Segment_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *Segment) GetRemoved() *SegmentRemoved {
	if x != nil {
		if x, ok := x.Info.(*Segment_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

type isSegment_Info interface {
	isSegment_Info()
}

type Segment_Updated struct {
	Updated *SegmentInfo `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type Segment_Removed struct {
	Removed *SegmentRemoved `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

func (*Segment_Updated) isSegment_Info() {}

func (*Segment_Removed) isSegment_Info() {}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeCreated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timeCreated,proto3" json:"timeCreated,omitempty"`
	TimeFinished  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timeFinished,proto3" json:"timeFinished,omitempty"`
	Lifetime      *durationpb.Duration   `protobuf:"bytes,4,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Keep          bool                   `protobuf:"varint,8,opt,name=keep,proto3" json:"keep,omitempty"`
	State         SessionState           `protobuf:"varint,9,opt,name=state,proto3,enum=sessionsource.SessionState" json:"state,omitempty"`
	Segments      []*Segment             `protobuf:"bytes,10,rep,name=segments,proto3" json:"segments,omitempty"`
	InlineFiles   *SessionInfo_Files     `protobuf:"bytes,11,opt,name=inlineFiles,proto3" json:"inlineFiles,omitempty"`
	DownloadFiles *SessionInfo_Files     `protobuf:"bytes,12,opt,name=downloadFiles,proto3" json:"downloadFiles,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,13,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// Estimated recording duration. Set when session transitions to PROCESSING
	// (estimated from chunk data), updated with exact value after rendering.
	Duration      *durationpb.Duration `protobuf:"bytes,14,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_sessionsource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{7}
}

func (x *SessionInfo) GetTimeCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCreated
	}
	return nil
}

func (x *SessionInfo) GetTimeFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFinished
	}
	return nil
}

func (x *SessionInfo) GetLifetime() *durationpb.Duration {
	if x != nil {
		return x.Lifetime
	}
	return nil
}

func (x *SessionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionInfo) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNKNOWN
}

func (x *SessionInfo) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *SessionInfo) GetInlineFiles() *SessionInfo_Files {
	if x != nil {
		return x.InlineFiles
	}
	return nil
}

func (x *SessionInfo) GetDownloadFiles() *SessionInfo_Files {
	if x != nil {
		return x.DownloadFiles
	}
	return nil
}

func (x *SessionInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SessionInfo) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type SessionRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRemoved) Reset() {
	*x = SessionRemoved{}
	mi := &file_sessionsource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRemoved) ProtoMessage() {}

func (x *SessionRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRemoved.ProtoReflect.Descriptor instead.
func (*SessionRemoved) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{8}
}

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Types that are valid to be assigned to Info:
	//
	//	*Session_Updated
	//	*Session_Removed
	Info          isSession_Info `protobuf_oneof:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_sessionsource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{9}
}

func (x *Session) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Session) GetInfo() isSession_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Session) GetUpdated() *SessionInfo {
	if x != nil {
		if x, ok := x.Info.(*Session_Updated); ok {
			return x.Updated
		}
	}
	return nil
}

func (x *Session) GetRemoved() *SessionRemoved {
	if x != nil {
		if x, ok := x.Info.(*Session_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

type isSession_Info interface {
	isSession_Info()
}

type Session_Updated struct {
	Updated *SessionInfo `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type Session_Removed struct {
	Removed *SessionRemoved `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

func (*Session_Updated) isSession_Info() {}

func (*Session_Removed) isSession_Info() {}

type SetKeepSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Keep          bool                   `protobuf:"varint,3,opt,name=keep,proto3" json:"keep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeepSessionRequest) Reset() {
	*x = SetKeepSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeepSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeepSessionRequest) ProtoMessage() {}

func (x *SetKeepSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeepSessionRequest.ProtoReflect.Descriptor instead.
func (*SetKeepSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{10}
}

func (x *SetKeepSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *SetKeepSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SetKeepSessionRequest) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *DeleteSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type SetNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNameRequest) Reset() {
	*x = SetNameRequest{}
	mi := &file_sessionsource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNameRequest) ProtoMessage() {}

func (x *SetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNameRequest.ProtoReflect.Descriptor instead.
func (*SetNameRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{12}
}

func (x *SetNameRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *SetNameRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SetNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SegmentID     string                 `protobuf:"bytes,3,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	Info          *SegmentInfo           `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentRequest) Reset() {
	*x = CreateSegmentRequest{}
	mi := &file_sessionsource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentRequest) ProtoMessage() {}

func (x *CreateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSegmentRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *CreateSegmentRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *CreateSegmentRequest) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

func (x *CreateSegmentRequest) GetInfo() *SegmentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SegmentID     string                 `protobuf:"bytes,3,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	Info          *SegmentInfo           `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSegmentRequest) Reset() {
	*x = UpdateSegmentRequest{}
	mi := &file_sessionsource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSegmentRequest) ProtoMessage() {}

func (x *UpdateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSegmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSegmentRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *UpdateSegmentRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *UpdateSegmentRequest) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

func (x *UpdateSegmentRequest) GetInfo() *SegmentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeleteSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SegmentID     string                 `protobuf:"bytes,3,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentRequest) Reset() {
	*x = DeleteSegmentRequest{}
	mi := &file_sessionsource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentRequest) ProtoMessage() {}

func (x *DeleteSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSegmentRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSegmentRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *DeleteSegmentRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *DeleteSegmentRequest) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

type RenderSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SegmentID     string                 `protobuf:"bytes,3,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderSegmentRequest) Reset() {
	*x = RenderSegmentRequest{}
	mi := &file_sessionsource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderSegmentRequest) ProtoMessage() {}

func (x *RenderSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderSegmentRequest.ProtoReflect.Descriptor instead.
func (*RenderSegmentRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{16}
}

func (x *RenderSegmentRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *RenderSegmentRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *RenderSegmentRequest) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

type CutSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutSessionRequest) Reset() {
	*x = CutSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutSessionRequest) ProtoMessage() {}

func (x *CutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutSessionRequest.ProtoReflect.Descriptor instead.
func (*CutSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{17}
}

func (x *CutSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

type RetryRenderSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecorderID    string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID     string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRenderSessionRequest) Reset() {
	*x = RetryRenderSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRenderSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRenderSessionRequest) ProtoMessage() {}

func (x *RetryRenderSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRenderSessionRequest.ProtoReflect.Descriptor instead.
func (*RetryRenderSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{18}
}

func (x *RetryRenderSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *RetryRenderSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type ShareSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecorderID      string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID       string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	RecipientEmails []string               `protobuf:"bytes,3,rep,name=recipientEmails,proto3" json:"recipientEmails,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShareSessionRequest) Reset() {
	*x = ShareSessionRequest{}
	mi := &file_sessionsource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareSessionRequest) ProtoMessage() {}

func (x *ShareSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareSessionRequest.ProtoReflect.Descriptor instead.
func (*ShareSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{19}
}

func (x *ShareSessionRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *ShareSessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ShareSessionRequest) GetRecipientEmails() []string {
	if x != nil {
		return x.RecipientEmails
	}
	return nil
}

type ShareSegmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecorderID      string                 `protobuf:"bytes,1,opt,name=recorderID,proto3" json:"recorderID,omitempty"`
	SessionID       string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	SegmentID       string                 `protobuf:"bytes,3,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	RecipientEmails []string               `protobuf:"bytes,4,rep,name=recipientEmails,proto3" json:"recipientEmails,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShareSegmentRequest) Reset() {
	*x = ShareSegmentRequest{}
	mi := &file_sessionsource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareSegmentRequest) ProtoMessage() {}

func (x *ShareSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareSegmentRequest.ProtoReflect.Descriptor instead.
func (*ShareSegmentRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{20}
}

func (x *ShareSegmentRequest) GetRecorderID() string {
	if x != nil {
		return x.RecorderID
	}
	return ""
}

func (x *ShareSegmentRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ShareSegmentRequest) GetSegmentID() string {
	if x != nil {
		return x.SegmentID
	}
	return ""
}

func (x *ShareSegmentRequest) GetRecipientEmails() []string {
	if x != nil {
		return x.RecipientEmails
	}
	return nil
}

type StreamSessionAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSessionAudioRequest) Reset() {
	*x = StreamSessionAudioRequest{}
	mi := &file_sessionsource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSessionAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSessionAudioRequest) ProtoMessage() {}

func (x *StreamSessionAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSessionAudioRequest.ProtoReflect.Descriptor instead.
func (*StreamSessionAudioRequest) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{21}
}

func (x *StreamSessionAudioRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Samples       []int32                `protobuf:"varint,2,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	ChunkNumber   uint32                 `protobuf:"varint,3,opt,name=chunkNumber,proto3" json:"chunkNumber,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_sessionsource_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{22}
}

func (x *AudioChunk) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AudioChunk) GetSamples() []int32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *AudioChunk) GetChunkNumber() uint32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *AudioChunk) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SegmentInfo_Files struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ogg           string                 `protobuf:"bytes,1,opt,name=ogg,proto3" json:"ogg,omitempty"`
	Flac          string                 `protobuf:"bytes,2,opt,name=flac,proto3" json:"flac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo_Files) Reset() {
	*x = SegmentInfo_Files{}
	mi := &file_sessionsource_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo_Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo_Files) ProtoMessage() {}

func (x *SegmentInfo_Files) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo_Files.ProtoReflect.Descriptor instead.
func (*SegmentInfo_Files) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SegmentInfo_Files) GetOgg() string {
	if x != nil {
		return x.Ogg
	}
	return ""
}

func (x *SegmentInfo_Files) GetFlac() string {
	if x != nil {
		return x.Flac
	}
	return ""
}

type SessionInfo_Files struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ogg           string                 `protobuf:"bytes,1,opt,name=ogg,proto3" json:"ogg,omitempty"`
	Flac          string                 `protobuf:"bytes,2,opt,name=flac,proto3" json:"flac,omitempty"`
	Waveform      string                 `protobuf:"bytes,3,opt,name=waveform,proto3" json:"waveform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo_Files) Reset() {
	*x = SessionInfo_Files{}
	mi := &file_sessionsource_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo_Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo_Files) ProtoMessage() {}

func (x *SessionInfo_Files) ProtoReflect() protoreflect.Message {
	mi := &file_sessionsource_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo_Files.ProtoReflect.Descriptor instead.
func (*SessionInfo_Files) Descriptor() ([]byte, []int) {
	return file_sessionsource_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SessionInfo_Files) GetOgg() string {
	if x != nil {
		return x.Ogg
	}
	return ""
}

func (x *SessionInfo_Files) GetFlac() string {
	if x != nil {
		return x.Flac
	}
	return ""
}

func (x *SessionInfo_Files) GetWaveform() string {
	if x != nil {
		return x.Waveform
	}
	return ""
}

var File_sessionsource_proto protoreflect.FileDescriptor

const file_sessionsource_proto_rawDesc = "" +
	"\n" +
	"\x13sessionsource.proto\x12\rsessionsource\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x18\n" +
	"\x16StreamRecordersRequest\"\x12\n" +
	"\x10RecordereRemoved\"\xc5\x01\n" +
	"\bRecorder\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\"\n" +
	"\frecorderName\x18\x02 \x01(\tR\frecorderName\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x16.common.RecorderStatusH\x00R\x06status\x12;\n" +
	"\aremoved\x18\x04 \x01(\v2\x1f.sessionsource.RecordereRemovedH\x00R\aremovedB\x06\n" +
	"\x04info\"6\n" +
	"\x14StreamSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\"\xa3\x03\n" +
	"\vSegmentInfo\x128\n" +
	"\ttimeStart\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x124\n" +
	"\atimeEnd\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1b.sessionsource.SegmentStateR\x05state\x12B\n" +
	"\vinlineFiles\x18\x05 \x01(\v2 .sessionsource.SegmentInfo.FilesR\vinlineFiles\x12F\n" +
	"\rdownloadFiles\x18\x06 \x01(\v2 .sessionsource.SegmentInfo.FilesR\rdownloadFiles\x12\"\n" +
	"\ferrorMessage\x18\a \x01(\tR\ferrorMessage\x1a-\n" +
	"\x05Files\x12\x10\n" +
	"\x03ogg\x18\x01 \x01(\tR\x03ogg\x12\x12\n" +
	"\x04flac\x18\x02 \x01(\tR\x04flac\"\x10\n" +
	"\x0eSegmentRemoved\"\xa2\x01\n" +
	"\aSegment\x12\x1c\n" +
	"\tsegmentID\x18\x01 \x01(\tR\tsegmentID\x126\n" +
	"\aupdated\x18\x02 \x01(\v2\x1a.sessionsource.SegmentInfoH\x00R\aupdated\x129\n" +
	"\aremoved\x18\x03 \x01(\v2\x1d.sessionsource.SegmentRemovedH\x00R\aremovedB\x06\n" +
	"\x04info\"\x83\x05\n" +
	"\vSessionInfo\x12<\n" +
	"\vtimeCreated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeCreated\x12>\n" +
	"\ftimeFinished\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeFinished\x125\n" +
	"\blifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\blifetime\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04keep\x18\b \x01(\bR\x04keep\x121\n" +
	"\x05state\x18\t \x01(\x0e2\x1b.sessionsource.SessionStateR\x05state\x122\n" +
	"\bsegments\x18\n" +
	" \x03(\v2\x16.sessionsource.SegmentR\bsegments\x12B\n" +
	"\vinlineFiles\x18\v \x01(\v2 .sessionsource.SessionInfo.FilesR\vinlineFiles\x12F\n" +
	"\rdownloadFiles\x18\f \x01(\v2 .sessionsource.SessionInfo.FilesR\rdownloadFiles\x12\"\n" +
	"\ferrorMessage\x18\r \x01(\tR\ferrorMessage\x125\n" +
	"\bduration\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\bduration\x1aI\n" +
	"\x05Files\x12\x10\n" +
	"\x03ogg\x18\x01 \x01(\tR\x03ogg\x12\x12\n" +
	"\x04flac\x18\x02 \x01(\tR\x04flac\x12\x1a\n" +
	"\bwaveform\x18\x03 \x01(\tR\bwaveform\"\x10\n" +
	"\x0eSessionRemoved\"\x94\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x126\n" +
	"\aupdated\x18\x02 \x01(\v2\x1a.sessionsource.SessionInfoH\x00R\aupdated\x129\n" +
	"\aremoved\x18\x03 \x01(\v2\x1d.sessionsource.SessionRemovedH\x00R\aremovedB\x06\n" +
	"\x04info\"i\n" +
	"\x15SetKeepSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x12\n" +
	"\x04keep\x18\x03 \x01(\bR\x04keep\"T\n" +
	"\x14DeleteSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\"b\n" +
	"\x0eSetNameRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa2\x01\n" +
	"\x14CreateSegmentRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1c\n" +
	"\tsegmentID\x18\x03 \x01(\tR\tsegmentID\x12.\n" +
	"\x04info\x18\x04 \x01(\v2\x1a.sessionsource.SegmentInfoR\x04info\"\xa2\x01\n" +
	"\x14UpdateSegmentRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1c\n" +
	"\tsegmentID\x18\x03 \x01(\tR\tsegmentID\x12.\n" +
	"\x04info\x18\x04 \x01(\v2\x1a.sessionsource.SegmentInfoR\x04info\"r\n" +
	"\x14DeleteSegmentRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1c\n" +
	"\tsegmentID\x18\x03 \x01(\tR\tsegmentID\"r\n" +
	"\x14RenderSegmentRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1c\n" +
	"\tsegmentID\x18\x03 \x01(\tR\tsegmentID\"3\n" +
	"\x11CutSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\"Y\n" +
	"\x19RetryRenderSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\"}\n" +
	"\x13ShareSessionRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12(\n" +
	"\x0frecipientEmails\x18\x03 \x03(\tR\x0frecipientEmails\"\x9b\x01\n" +
	"\x13ShareSegmentRequest\x12\x1e\n" +
	"\n" +
	"recorderID\x18\x01 \x01(\tR\n" +
	"recorderID\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x1c\n" +
	"\tsegmentID\x18\x03 \x01(\tR\tsegmentID\x12(\n" +
	"\x0frecipientEmails\x18\x04 \x03(\tR\x0frecipientEmails\"9\n" +
	"\x19StreamSessionAudioRequest\x12\x1c\n" +
	"\tsessionID\x18\x01 \x01(\tR\tsessionID\"\xa0\x01\n" +
	"\n" +
	"AudioChunk\x12\x1c\n" +
	"\tsessionID\x18\x01 \x01(\tR\tsessionID\x12\x18\n" +
	"\asamples\x18\x02 \x03(\x05R\asamples\x12 \n" +
	"\vchunkNumber\x18\x03 \x01(\rR\vchunkNumber\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\x95\x01\n" +
	"\fSegmentState\x12\x19\n" +
	"\x15SEGMENT_STATE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17SEGMENT_STATE_RENDERING\x10\x01\x12\x1a\n" +
	"\x16SEGMENT_STATE_FINISHED\x10\x02\x12\x17\n" +
	"\x13SEGMENT_STATE_ERROR\x10\x03\x12\x18\n" +
	"\x14SEGMENT_STATE_QUEUED\x10\x04*\x99\x01\n" +
	"\fSessionState\x12\x19\n" +
	"\x15SESSION_STATE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17SESSION_STATE_RECORDING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATE_FINISHED\x10\x02\x12\x1c\n" +
	"\x18SESSION_STATE_PROCESSING\x10\x03\x12\x17\n" +
	"\x13SESSION_STATE_ERROR\x10\x042\x95\b\n" +
	"\rSessionSource\x12S\n" +
	"\x0fStreamRecorders\x12%.sessionsource.StreamRecordersRequest\x1a\x17.sessionsource.Recorder0\x01\x12O\n" +
	"\x0eStreamSessions\x12#.sessionsource.StreamSessionRequest\x1a\x16.sessionsource.Session0\x01\x12[\n" +
	"\x12StreamSessionAudio\x12(.sessionsource.StreamSessionAudioRequest\x1a\x19.sessionsource.AudioChunk0\x01\x12G\n" +
	"\x0eSetKeepSession\x12$.sessionsource.SetKeepSessionRequest\x1a\x0f.common.Respone\x12E\n" +
	"\rDeleteSession\x12#.sessionsource.DeleteSessionRequest\x1a\x0f.common.Respone\x129\n" +
	"\aSetName\x12\x1d.sessionsource.SetNameRequest\x1a\x0f.common.Respone\x12E\n" +
	"\rCreateSegment\x12#.sessionsource.CreateSegmentRequest\x1a\x0f.common.Respone\x12E\n" +
	"\rDeleteSegment\x12#.sessionsource.DeleteSegmentRequest\x1a\x0f.common.Respone\x12E\n" +
	"\rRenderSegment\x12#.sessionsource.RenderSegmentRequest\x1a\x0f.common.Respone\x12E\n" +
	"\rUpdateSegment\x12#.sessionsource.UpdateSegmentRequest\x1a\x0f.common.Respone\x12?\n" +
	"\n" +
	"CutSession\x12 .sessionsource.CutSessionRequest\x1a\x0f.common.Respone\x12O\n" +
	"\x12RetryRenderSession\x12(.sessionsource.RetryRenderSessionRequest\x1a\x0f.common.Respone\x12C\n" +
	"\fShareSession\x12\".sessionsource.ShareSessionRequest\x1a\x0f.common.Respone\x12C\n" +
	"\fShareSegment\x12\".sessionsource.ShareSegmentRequest\x1a\x0f.common.ResponeBEZCgithub.com/pascalhuerst/session-recorder/protocols/go/sessionsourceb\x06proto3"

var (
	file_sessionsource_proto_rawDescOnce sync.Once
	file_sessionsource_proto_rawDescData []byte
)

func file_sessionsource_proto_rawDescGZIP() []byte {
	file_sessionsource_proto_rawDescOnce.Do(func() {
		file_sessionsource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessionsource_proto_rawDesc), len(file_sessionsource_proto_rawDesc)))
	})
	return file_sessionsource_proto_rawDescData
}

var file_sessionsource_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sessionsource_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_sessionsource_proto_goTypes = []any{
	(SegmentState)(0),                 // 0: sessionsource.SegmentState
	(SessionState)(0),                 // 1: sessionsource.SessionState
	(*StreamRecordersRequest)(nil),    // 2: sessionsource.StreamRecordersRequest
	(*RecordereRemoved)(nil),          // 3: sessionsource.RecordereRemoved
	(*Recorder)(nil),                  // 4: sessionsource.Recorder
	(*StreamSessionRequest)(nil),      // 5: sessionsource.StreamSessionRequest
	(*SegmentInfo)(nil),               // 6: sessionsource.SegmentInfo
	(*SegmentRemoved)(nil),            // 7: sessionsource.SegmentRemoved
	(*Segment)(nil),                   // 8: sessionsource.Segment
	(*SessionInfo)(nil),               // 9: sessionsource.SessionInfo
	(*SessionRemoved)(nil),            // 10: sessionsource.SessionRemoved
	(*Session)(nil),                   // 11: sessionsource.Session
	(*SetKeepSessionRequest)(nil),     // 12: sessionsource.SetKeepSessionRequest
	(*DeleteSessionRequest)(nil),      // 13: sessionsource.DeleteSessionRequest
	(*SetNameRequest)(nil),            // 14: sessionsource.SetNameRequest
	(*CreateSegmentRequest)(nil),      // 15: sessionsource.CreateSegmentRequest
	(*UpdateSegmentRequest)(nil),      // 16: sessionsource.UpdateSegmentRequest
	(*DeleteSegmentRequest)(nil),      // 17: sessionsource.DeleteSegmentRequest
	(*RenderSegmentRequest)(nil),      // 18: sessionsource.RenderSegmentRequest
	(*CutSessionRequest)(nil),         // 19: sessionsource.CutSessionRequest
	(*RetryRenderSessionRequest)(nil), // 20: sessionsource.RetryRenderSessionRequest
	(*ShareSessionRequest)(nil),       // 21: sessionsource.ShareSessionRequest
	(*ShareSegmentRequest)(nil),       // 22: sessionsource.ShareSegmentRequest
	(*StreamSessionAudioRequest)(nil), // 23: sessionsource.StreamSessionAudioRequest
	(*AudioChunk)(nil),                // 24: sessionsource.AudioChunk
	(*SegmentInfo_Files)(nil),         // 25: sessionsource.SegmentInfo.Files
	(*SessionInfo_Files)(nil),         // 26: sessionsource.SessionInfo.Files
	(*common.RecorderStatus)(nil),     // 27: common.RecorderStatus
	(*timestamppb.Timestamp)(nil),     // 28: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),       // 29: google.protobuf.Duration
	(*common.Respone)(nil),            // 30: common.Respone
}
var file_sessionsource_proto_depIdxs = []int32{
	27, // 0: sessionsource.Recorder.status:type_name -> common.RecorderStatus
	3,  // 1: sessionsource.Recorder.removed:type_name -> sessionsource.RecordereRemoved
	28, // 2: sessionsource.SegmentInfo.timeStart:type_name -> google.protobuf.Timestamp
	28, // 3: sessionsource.SegmentInfo.timeEnd:type_name -> google.protobuf.Timestamp
	0,  // 4: sessionsource.SegmentInfo.state:type_name -> sessionsource.SegmentState
	25, // 5: sessionsource.SegmentInfo.inlineFiles:type_name -> sessionsource.SegmentInfo.Files
	25, // 6: sessionsource.SegmentInfo.downloadFiles:type_name -> sessionsource.SegmentInfo.Files
	6,  // 7: sessionsource.Segment.updated:type_name -> sessionsource.SegmentInfo
	7,  // 8: sessionsource.Segment.removed:type_name -> sessionsource.SegmentRemoved
	28, // 9: sessionsource.SessionInfo.timeCreated:type_name -> google.protobuf.Timestamp
	28, // 10: sessionsource.SessionInfo.timeFinished:type_name -> google.protobuf.Timestamp
	29, // 11: sessionsource.SessionInfo.lifetime:type_name -> google.protobuf.Duration
	1,  // 12: sessionsource.SessionInfo.state:type_name -> sessionsource.SessionState
	8,  // 13: sessionsource.SessionInfo.segments:type_name -> sessionsource.Segment
	26, // 14: sessionsource.SessionInfo.inlineFiles:type_name -> sessionsource.SessionInfo.Files
	26, // 15: sessionsource.SessionInfo.downloadFiles:type_name -> sessionsource.SessionInfo.Files
	29, // 16: sessionsource.SessionInfo.duration:type_name -> google.protobuf.Duration
	9,  // 17: sessionsource.Session.updated:type_name -> sessionsource.SessionInfo
	10, // 18: sessionsource.Session.removed:type_name -> sessionsource.SessionRemoved
	6,  // 19: sessionsource.CreateSegmentRequest.info:type_name -> sessionsource.SegmentInfo
	6,  // 20: sessionsource.UpdateSegmentRequest.info:type_name -> sessionsource.SegmentInfo
	28, // 21: sessionsource.AudioChunk.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 22: sessionsource.SessionSource.StreamRecorders:input_type -> sessionsource.StreamRecordersRequest
	5,  // 23: sessionsource.SessionSource.StreamSessions:input_type -> sessionsource.StreamSessionRequest
	23, // 24: sessionsource.SessionSource.StreamSessionAudio:input_type -> sessionsource.StreamSessionAudioRequest
	12, // 25: sessionsource.SessionSource.SetKeepSession:input_type -> sessionsource.SetKeepSessionRequest
	13, // 26: sessionsource.SessionSource.DeleteSession:input_type -> sessionsource.DeleteSessionRequest
	14, // 27: sessionsource.SessionSource.SetName:input_type -> sessionsource.SetNameRequest
	15, // 28: sessionsource.SessionSource.CreateSegment:input_type -> sessionsource.CreateSegmentRequest
	17, // 29: sessionsource.SessionSource.DeleteSegment:input_type -> sessionsource.DeleteSegmentRequest
	18, // 30: sessionsource.SessionSource.RenderSegment:input_type -> sessionsource.RenderSegmentRequest
	16, // 31: sessionsource.SessionSource.UpdateSegment:input_type -> sessionsource.UpdateSegmentRequest
	19, // 32: sessionsource.SessionSource.CutSession:input_type -> sessionsource.CutSessionRequest
	20, // 33: sessionsource.SessionSource.RetryRenderSession:input_type -> sessionsource.RetryRenderSessionRequest
	21, // 34: sessionsource.SessionSource.ShareSession:input_type -> sessionsource.ShareSessionRequest
	22, // 35: sessionsource.SessionSource.ShareSegment:input_type -> sessionsource.ShareSegmentRequest
	4,  // 36: sessionsource.SessionSource.StreamRecorders:output_type -> sessionsource.Recorder
	11, // 37: sessionsource.SessionSource.StreamSessions:output_type -> sessionsource.Session
	24, // 38: sessionsource.SessionSource.StreamSessionAudio:output_type -> sessionsource.AudioChunk
	30, // 39: sessionsource.SessionSource.SetKeepSession:output_type -> common.Respone
	30, // 40: sessionsource.SessionSource.DeleteSession:output_type -> common.Respone
	30, // 41: sessionsource.SessionSource.SetName:output_type -> common.Respone
	30, // 42: sessionsource.SessionSource.CreateSegment:output_type -> common.Respone
	30, // 43: sessionsource.SessionSource.DeleteSegment:output_type -> common.Respone
	30, // 44: sessionsource.SessionSource.RenderSegment:output_type -> common.Respone
	30, // 45: sessionsource.SessionSource.UpdateSegment:output_type -> common.Respone
	30, // 46: sessionsource.SessionSource.CutSession:output_type -> common.Respone
	30, // 47: sessionsource.SessionSource.RetryRenderSession:output_type -> common.Respone
	30, // 48: sessionsource.SessionSource.ShareSession:output_type -> common.Respone
	30, // 49: sessionsource.SessionSource.ShareSegment:output_type -> common.Respone
	36, // [36:50] is the sub-list for method output_type
	22, // [22:36] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_sessionsource_proto_init() }
func file_sessionsource_proto_init() {
	if File_sessionsource_proto != nil {
		return
	}
	file_sessionsource_proto_msgTypes[2].OneofWrappers = []any{
		(*Recorder_Status)(nil),
		(*Recorder_Removed)(nil),
	}
	file_sessionsource_proto_msgTypes[6].OneofWrappers = []any{
		(*Segment_Updated)(nil),
		(*Segment_Removed)(nil),
	}
	file_sessionsource_proto_msgTypes[9].OneofWrappers = []any{
		(*Session_Updated)(nil),
		(*Session_Removed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessionsource_proto_rawDesc), len(file_sessionsource_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessionsource_proto_goTypes,
		DependencyIndexes: file_sessionsource_proto_depIdxs,
		EnumInfos:         file_sessionsource_proto_enumTypes,
		MessageInfos:      file_sessionsource_proto_msgTypes,
	}.Build()
	File_sessionsource_proto = out.File
	file_sessionsource_proto_goTypes = nil
	file_sessionsource_proto_depIdxs = nil
}
