// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chunksource.proto
#ifndef GRPC_chunksource_2eproto__INCLUDED
#define GRPC_chunksource_2eproto__INCLUDED

#include "chunksource.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace chunksource {

class ChunkSource final {
 public:
  static constexpr char const* service_full_name() {
    return "chunksource.ChunkSource";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::chunksource::ChunkSourceInfo>> StreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::chunksource::ChunkSourceInfo>>(StreamChunkSourceStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>> AsyncStreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>>(AsyncStreamChunkSourceStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>> PrepareAsyncStreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>>(PrepareAsyncStreamChunkSourceStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest* request, ::grpc::ClientReadReactor< ::chunksource::ChunkSourceInfo>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::chunksource::ChunkSourceInfo>* StreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>* AsyncStreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chunksource::ChunkSourceInfo>* PrepareAsyncStreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::chunksource::ChunkSourceInfo>> StreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::chunksource::ChunkSourceInfo>>(StreamChunkSourceStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>> AsyncStreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>>(AsyncStreamChunkSourceStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>> PrepareAsyncStreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>>(PrepareAsyncStreamChunkSourceStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamChunkSourceStatus(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest* request, ::grpc::ClientReadReactor< ::chunksource::ChunkSourceInfo>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::chunksource::ChunkSourceInfo>* StreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request) override;
    ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>* AsyncStreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::chunksource::ChunkSourceInfo>* PrepareAsyncStreamChunkSourceStatusRaw(::grpc::ClientContext* context, const ::chunksource::StreamChunkSourceStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamChunkSourceStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* context, const ::chunksource::StreamChunkSourceStatusRequest* request, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChunkSourceStatus(::grpc::ServerContext* context, ::chunksource::StreamChunkSourceStatusRequest* request, ::grpc::ServerAsyncWriter< ::chunksource::ChunkSourceInfo>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamChunkSourceStatus<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::chunksource::StreamChunkSourceStatusRequest, ::chunksource::ChunkSourceInfo>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chunksource::StreamChunkSourceStatusRequest* request) { return this->StreamChunkSourceStatus(context, request); }));
    }
    ~WithCallbackMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::chunksource::ChunkSourceInfo>* StreamChunkSourceStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamChunkSourceStatus<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChunkSourceStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamChunkSourceStatus(context, request); }));
    }
    ~WithRawCallbackMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamChunkSourceStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamChunkSourceStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamChunkSourceStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::chunksource::StreamChunkSourceStatusRequest, ::chunksource::ChunkSourceInfo>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::chunksource::StreamChunkSourceStatusRequest, ::chunksource::ChunkSourceInfo>* streamer) {
                       return this->StreamedStreamChunkSourceStatus(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamChunkSourceStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamChunkSourceStatus(::grpc::ServerContext* /*context*/, const ::chunksource::StreamChunkSourceStatusRequest* /*request*/, ::grpc::ServerWriter< ::chunksource::ChunkSourceInfo>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamChunkSourceStatus(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::chunksource::StreamChunkSourceStatusRequest,::chunksource::ChunkSourceInfo>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamChunkSourceStatus<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamChunkSourceStatus<Service > StreamedService;
};

}  // namespace chunksource


#endif  // GRPC_chunksource_2eproto__INCLUDED
