// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chunksink.proto
#ifndef GRPC_chunksink_2eproto__INCLUDED
#define GRPC_chunksink_2eproto__INCLUDED

#include "chunksink.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace chunksink {

class ChunkSink final {
 public:
  static constexpr char const* service_full_name() {
    return "chunksink.ChunkSink";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::chunksink::ChunkData>> StreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::chunksink::ChunkData>>(StreamChunkDataRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>> AsyncStreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>>(AsyncStreamChunkDataRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>> PrepareAsyncStreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>>(PrepareAsyncStreamChunkDataRaw(context, request, cq));
    }
    virtual ::grpc::Status SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::chunksink::RecorderStatusReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>> AsyncSetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>>(AsyncSetRecorderStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>> PrepareAsyncSetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>>(PrepareAsyncSetRecorderStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest* request, ::grpc::ClientReadReactor< ::chunksink::ChunkData>* reactor) = 0;
      virtual void SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::chunksink::ChunkData>* StreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>* AsyncStreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::chunksink::ChunkData>* PrepareAsyncStreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>* AsyncSetRecorderStatusRaw(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chunksink::RecorderStatusReply>* PrepareAsyncSetRecorderStatusRaw(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::chunksink::ChunkData>> StreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::chunksink::ChunkData>>(StreamChunkDataRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksink::ChunkData>> AsyncStreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksink::ChunkData>>(AsyncStreamChunkDataRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksink::ChunkData>> PrepareAsyncStreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::chunksink::ChunkData>>(PrepareAsyncStreamChunkDataRaw(context, request, cq));
    }
    ::grpc::Status SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::chunksink::RecorderStatusReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>> AsyncSetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>>(AsyncSetRecorderStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>> PrepareAsyncSetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>>(PrepareAsyncSetRecorderStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamChunkData(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest* request, ::grpc::ClientReadReactor< ::chunksink::ChunkData>* reactor) override;
      void SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response, std::function<void(::grpc::Status)>) override;
      void SetRecorderStatus(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::chunksink::ChunkData>* StreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request) override;
    ::grpc::ClientAsyncReader< ::chunksink::ChunkData>* AsyncStreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::chunksink::ChunkData>* PrepareAsyncStreamChunkDataRaw(::grpc::ClientContext* context, const ::chunksink::StreamChunkDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>* AsyncSetRecorderStatusRaw(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chunksink::RecorderStatusReply>* PrepareAsyncSetRecorderStatusRaw(::grpc::ClientContext* context, const ::chunksink::RecorderStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamChunkData_;
    const ::grpc::internal::RpcMethod rpcmethod_SetRecorderStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamChunkData(::grpc::ServerContext* context, const ::chunksink::StreamChunkDataRequest* request, ::grpc::ServerWriter< ::chunksink::ChunkData>* writer);
    virtual ::grpc::Status SetRecorderStatus(::grpc::ServerContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChunkData(::grpc::ServerContext* context, ::chunksink::StreamChunkDataRequest* request, ::grpc::ServerAsyncWriter< ::chunksink::ChunkData>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRecorderStatus(::grpc::ServerContext* context, ::chunksink::RecorderStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::chunksink::RecorderStatusReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamChunkData<WithAsyncMethod_SetRecorderStatus<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::chunksink::StreamChunkDataRequest, ::chunksink::ChunkData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chunksink::StreamChunkDataRequest* request) { return this->StreamChunkData(context, request); }));
    }
    ~WithCallbackMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::chunksink::ChunkData>* StreamChunkData(
      ::grpc::CallbackServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::chunksink::RecorderStatusRequest, ::chunksink::RecorderStatusReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chunksink::RecorderStatusRequest* request, ::chunksink::RecorderStatusReply* response) { return this->SetRecorderStatus(context, request, response); }));}
    void SetMessageAllocatorFor_SetRecorderStatus(
        ::grpc::MessageAllocator< ::chunksink::RecorderStatusRequest, ::chunksink::RecorderStatusReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chunksink::RecorderStatusRequest, ::chunksink::RecorderStatusReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRecorderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamChunkData<WithCallbackMethod_SetRecorderStatus<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamChunkData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRecorderStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamChunkData(context, request); }));
    }
    ~WithRawCallbackMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamChunkData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetRecorderStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetRecorderStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetRecorderStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetRecorderStatus() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chunksink::RecorderStatusRequest, ::chunksink::RecorderStatusReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chunksink::RecorderStatusRequest, ::chunksink::RecorderStatusReply>* streamer) {
                       return this->StreamedSetRecorderStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetRecorderStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetRecorderStatus(::grpc::ServerContext* /*context*/, const ::chunksink::RecorderStatusRequest* /*request*/, ::chunksink::RecorderStatusReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetRecorderStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chunksink::RecorderStatusRequest,::chunksink::RecorderStatusReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetRecorderStatus<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamChunkData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamChunkData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::chunksink::StreamChunkDataRequest, ::chunksink::ChunkData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::chunksink::StreamChunkDataRequest, ::chunksink::ChunkData>* streamer) {
                       return this->StreamedStreamChunkData(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamChunkData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamChunkData(::grpc::ServerContext* /*context*/, const ::chunksink::StreamChunkDataRequest* /*request*/, ::grpc::ServerWriter< ::chunksink::ChunkData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamChunkData(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::chunksink::StreamChunkDataRequest,::chunksink::ChunkData>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamChunkData<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamChunkData<WithStreamedUnaryMethod_SetRecorderStatus<Service > > StreamedService;
};

}  // namespace chunksink


#endif  // GRPC_chunksink_2eproto__INCLUDED
