// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chunksink.proto

#include "chunksink.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace chunksink {
PROTOBUF_CONSTEXPR Chunks::Chunks(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._data_cached_byte_size_)*/{0}
  , /*decltype(_impl_.recorderid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sessionid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timecreated_)*/nullptr
  , /*decltype(_impl_.chunkcount_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ChunksDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChunksDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChunksDefaultTypeInternal() {}
  union {
    Chunks _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChunksDefaultTypeInternal _Chunks_default_instance_;
PROTOBUF_CONSTEXPR GetCommandRequest::GetCommandRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.recorderid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetCommandRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetCommandRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetCommandRequestDefaultTypeInternal() {}
  union {
    GetCommandRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetCommandRequestDefaultTypeInternal _GetCommandRequest_default_instance_;
PROTOBUF_CONSTEXPR CmdCutSession::CmdCutSession(
    ::_pbi::ConstantInitialized) {}
struct CmdCutSessionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CmdCutSessionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CmdCutSessionDefaultTypeInternal() {}
  union {
    CmdCutSession _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CmdCutSessionDefaultTypeInternal _CmdCutSession_default_instance_;
PROTOBUF_CONSTEXPR Reboot::Reboot(
    ::_pbi::ConstantInitialized) {}
struct RebootDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RebootDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RebootDefaultTypeInternal() {}
  union {
    Reboot _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RebootDefaultTypeInternal _Reboot_default_instance_;
PROTOBUF_CONSTEXPR Command::Command(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct CommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandDefaultTypeInternal() {}
  union {
    Command _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandDefaultTypeInternal _Command_default_instance_;
}  // namespace chunksink
static ::_pb::Metadata file_level_metadata_chunksink_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_chunksink_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_chunksink_2eproto = nullptr;

const uint32_t TableStruct_chunksink_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _impl_.recorderid_),
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _impl_.sessionid_),
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _impl_.chunkcount_),
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _impl_.timecreated_),
  PROTOBUF_FIELD_OFFSET(::chunksink::Chunks, _impl_.data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chunksink::GetCommandRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::chunksink::GetCommandRequest, _impl_.recorderid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chunksink::CmdCutSession, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chunksink::Reboot, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::chunksink::Command, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::chunksink::Command, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::chunksink::Command, _impl_.command_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::chunksink::Chunks)},
  { 11, -1, -1, sizeof(::chunksink::GetCommandRequest)},
  { 18, -1, -1, sizeof(::chunksink::CmdCutSession)},
  { 24, -1, -1, sizeof(::chunksink::Reboot)},
  { 30, -1, -1, sizeof(::chunksink::Command)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::chunksink::_Chunks_default_instance_._instance,
  &::chunksink::_GetCommandRequest_default_instance_._instance,
  &::chunksink::_CmdCutSession_default_instance_._instance,
  &::chunksink::_Reboot_default_instance_._instance,
  &::chunksink::_Command_default_instance_._instance,
};

const char descriptor_table_protodef_chunksink_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017chunksink.proto\022\tchunksink\032\014common.pro"
  "to\032\037google/protobuf/timestamp.proto\"\202\001\n\006"
  "Chunks\022\022\n\nrecorderID\030\001 \001(\t\022\021\n\tsessionID\030"
  "\002 \001(\t\022\022\n\nchunkCount\030\003 \001(\r\022/\n\013timeCreated"
  "\030\004 \001(\0132\032.google.protobuf.Timestamp\022\014\n\004da"
  "ta\030\005 \003(\r\"\'\n\021GetCommandRequest\022\022\n\nrecorde"
  "rID\030\001 \001(\t\"\017\n\rCmdCutSession\"\010\n\006Reboot\"l\n\007"
  "Command\022#\n\006reboot\030\001 \001(\0132\021.chunksink.Rebo"
  "otH\000\0221\n\rcmdCutSession\030\002 \001(\0132\030.chunksink."
  "CmdCutSessionH\000B\t\n\007command2\275\001\n\tChunkSink"
  "\022<\n\021SetRecorderStatus\022\026.common.RecorderS"
  "tatus\032\017.common.Respone\022/\n\tSetChunks\022\021.ch"
  "unksink.Chunks\032\017.common.Respone\022A\n\013GetCo"
  "mmands\022\034.chunksink.GetCommandRequest\032\022.c"
  "hunksink.Command0\001BAZ\?github.com/pascalh"
  "uerst/session-recorder/protocols/go/chun"
  "ksinkb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_chunksink_2eproto_deps[2] = {
  &::descriptor_table_common_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_chunksink_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_chunksink_2eproto = {
    false, false, 653, descriptor_table_protodef_chunksink_2eproto,
    "chunksink.proto",
    &descriptor_table_chunksink_2eproto_once, descriptor_table_chunksink_2eproto_deps, 2, 5,
    schemas, file_default_instances, TableStruct_chunksink_2eproto::offsets,
    file_level_metadata_chunksink_2eproto, file_level_enum_descriptors_chunksink_2eproto,
    file_level_service_descriptors_chunksink_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_chunksink_2eproto_getter() {
  return &descriptor_table_chunksink_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_chunksink_2eproto(&descriptor_table_chunksink_2eproto);
namespace chunksink {

// ===================================================================

class Chunks::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timecreated(const Chunks* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
Chunks::_Internal::timecreated(const Chunks* msg) {
  return *msg->_impl_.timecreated_;
}
void Chunks::clear_timecreated() {
  if (GetArenaForAllocation() == nullptr && _impl_.timecreated_ != nullptr) {
    delete _impl_.timecreated_;
  }
  _impl_.timecreated_ = nullptr;
}
Chunks::Chunks(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chunksink.Chunks)
}
Chunks::Chunks(const Chunks& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Chunks* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , /*decltype(_impl_._data_cached_byte_size_)*/{0}
    , decltype(_impl_.recorderid_){}
    , decltype(_impl_.sessionid_){}
    , decltype(_impl_.timecreated_){nullptr}
    , decltype(_impl_.chunkcount_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.recorderid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recorderid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_recorderid().empty()) {
    _this->_impl_.recorderid_.Set(from._internal_recorderid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sessionid().empty()) {
    _this->_impl_.sessionid_.Set(from._internal_sessionid(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timecreated()) {
    _this->_impl_.timecreated_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timecreated_);
  }
  _this->_impl_.chunkcount_ = from._impl_.chunkcount_;
  // @@protoc_insertion_point(copy_constructor:chunksink.Chunks)
}

inline void Chunks::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , /*decltype(_impl_._data_cached_byte_size_)*/{0}
    , decltype(_impl_.recorderid_){}
    , decltype(_impl_.sessionid_){}
    , decltype(_impl_.timecreated_){nullptr}
    , decltype(_impl_.chunkcount_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.recorderid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recorderid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Chunks::~Chunks() {
  // @@protoc_insertion_point(destructor:chunksink.Chunks)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Chunks::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
  _impl_.recorderid_.Destroy();
  _impl_.sessionid_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timecreated_;
}

void Chunks::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Chunks::Clear() {
// @@protoc_insertion_point(message_clear_start:chunksink.Chunks)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _impl_.recorderid_.ClearToEmpty();
  _impl_.sessionid_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.timecreated_ != nullptr) {
    delete _impl_.timecreated_;
  }
  _impl_.timecreated_ = nullptr;
  _impl_.chunkcount_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Chunks::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string recorderID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_recorderid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chunksink.Chunks.recorderID"));
        } else
          goto handle_unusual;
        continue;
      // string sessionID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sessionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chunksink.Chunks.sessionID"));
        } else
          goto handle_unusual;
        continue;
      // uint32 chunkCount = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.chunkcount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp timeCreated = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_timecreated(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 40) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Chunks::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chunksink.Chunks)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string recorderID = 1;
  if (!this->_internal_recorderid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_recorderid().data(), static_cast<int>(this->_internal_recorderid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chunksink.Chunks.recorderID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_recorderid(), target);
  }

  // string sessionID = 2;
  if (!this->_internal_sessionid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sessionid().data(), static_cast<int>(this->_internal_sessionid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chunksink.Chunks.sessionID");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sessionid(), target);
  }

  // uint32 chunkCount = 3;
  if (this->_internal_chunkcount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_chunkcount(), target);
  }

  // .google.protobuf.Timestamp timeCreated = 4;
  if (this->_internal_has_timecreated()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::timecreated(this),
        _Internal::timecreated(this).GetCachedSize(), target, stream);
  }

  // repeated uint32 data = 5;
  {
    int byte_size = _impl_._data_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          5, _internal_data(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chunksink.Chunks)
  return target;
}

size_t Chunks::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chunksink.Chunks)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 data = 5;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.data_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string recorderID = 1;
  if (!this->_internal_recorderid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_recorderid());
  }

  // string sessionID = 2;
  if (!this->_internal_sessionid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sessionid());
  }

  // .google.protobuf.Timestamp timeCreated = 4;
  if (this->_internal_has_timecreated()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timecreated_);
  }

  // uint32 chunkCount = 3;
  if (this->_internal_chunkcount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_chunkcount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Chunks::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Chunks::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Chunks::GetClassData() const { return &_class_data_; }


void Chunks::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Chunks*>(&to_msg);
  auto& from = static_cast<const Chunks&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chunksink.Chunks)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (!from._internal_recorderid().empty()) {
    _this->_internal_set_recorderid(from._internal_recorderid());
  }
  if (!from._internal_sessionid().empty()) {
    _this->_internal_set_sessionid(from._internal_sessionid());
  }
  if (from._internal_has_timecreated()) {
    _this->_internal_mutable_timecreated()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timecreated());
  }
  if (from._internal_chunkcount() != 0) {
    _this->_internal_set_chunkcount(from._internal_chunkcount());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Chunks::CopyFrom(const Chunks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chunksink.Chunks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Chunks::IsInitialized() const {
  return true;
}

void Chunks::InternalSwap(Chunks* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.recorderid_, lhs_arena,
      &other->_impl_.recorderid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sessionid_, lhs_arena,
      &other->_impl_.sessionid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Chunks, _impl_.chunkcount_)
      + sizeof(Chunks::_impl_.chunkcount_)
      - PROTOBUF_FIELD_OFFSET(Chunks, _impl_.timecreated_)>(
          reinterpret_cast<char*>(&_impl_.timecreated_),
          reinterpret_cast<char*>(&other->_impl_.timecreated_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Chunks::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chunksink_2eproto_getter, &descriptor_table_chunksink_2eproto_once,
      file_level_metadata_chunksink_2eproto[0]);
}

// ===================================================================

class GetCommandRequest::_Internal {
 public:
};

GetCommandRequest::GetCommandRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chunksink.GetCommandRequest)
}
GetCommandRequest::GetCommandRequest(const GetCommandRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetCommandRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.recorderid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.recorderid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recorderid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_recorderid().empty()) {
    _this->_impl_.recorderid_.Set(from._internal_recorderid(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:chunksink.GetCommandRequest)
}

inline void GetCommandRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.recorderid_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.recorderid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.recorderid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetCommandRequest::~GetCommandRequest() {
  // @@protoc_insertion_point(destructor:chunksink.GetCommandRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetCommandRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.recorderid_.Destroy();
}

void GetCommandRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetCommandRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:chunksink.GetCommandRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.recorderid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetCommandRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string recorderID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_recorderid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "chunksink.GetCommandRequest.recorderID"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetCommandRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chunksink.GetCommandRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string recorderID = 1;
  if (!this->_internal_recorderid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_recorderid().data(), static_cast<int>(this->_internal_recorderid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "chunksink.GetCommandRequest.recorderID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_recorderid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chunksink.GetCommandRequest)
  return target;
}

size_t GetCommandRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chunksink.GetCommandRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string recorderID = 1;
  if (!this->_internal_recorderid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_recorderid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetCommandRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetCommandRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetCommandRequest::GetClassData() const { return &_class_data_; }


void GetCommandRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetCommandRequest*>(&to_msg);
  auto& from = static_cast<const GetCommandRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chunksink.GetCommandRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_recorderid().empty()) {
    _this->_internal_set_recorderid(from._internal_recorderid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetCommandRequest::CopyFrom(const GetCommandRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chunksink.GetCommandRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetCommandRequest::IsInitialized() const {
  return true;
}

void GetCommandRequest::InternalSwap(GetCommandRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.recorderid_, lhs_arena,
      &other->_impl_.recorderid_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata GetCommandRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chunksink_2eproto_getter, &descriptor_table_chunksink_2eproto_once,
      file_level_metadata_chunksink_2eproto[1]);
}

// ===================================================================

class CmdCutSession::_Internal {
 public:
};

CmdCutSession::CmdCutSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:chunksink.CmdCutSession)
}
CmdCutSession::CmdCutSession(const CmdCutSession& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  CmdCutSession* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:chunksink.CmdCutSession)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CmdCutSession::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CmdCutSession::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata CmdCutSession::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chunksink_2eproto_getter, &descriptor_table_chunksink_2eproto_once,
      file_level_metadata_chunksink_2eproto[2]);
}

// ===================================================================

class Reboot::_Internal {
 public:
};

Reboot::Reboot(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:chunksink.Reboot)
}
Reboot::Reboot(const Reboot& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Reboot* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:chunksink.Reboot)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Reboot::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Reboot::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Reboot::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chunksink_2eproto_getter, &descriptor_table_chunksink_2eproto_once,
      file_level_metadata_chunksink_2eproto[3]);
}

// ===================================================================

class Command::_Internal {
 public:
  static const ::chunksink::Reboot& reboot(const Command* msg);
  static const ::chunksink::CmdCutSession& cmdcutsession(const Command* msg);
};

const ::chunksink::Reboot&
Command::_Internal::reboot(const Command* msg) {
  return *msg->_impl_.command_.reboot_;
}
const ::chunksink::CmdCutSession&
Command::_Internal::cmdcutsession(const Command* msg) {
  return *msg->_impl_.command_.cmdcutsession_;
}
void Command::set_allocated_reboot(::chunksink::Reboot* reboot) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_command();
  if (reboot) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(reboot);
    if (message_arena != submessage_arena) {
      reboot = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reboot, submessage_arena);
    }
    set_has_reboot();
    _impl_.command_.reboot_ = reboot;
  }
  // @@protoc_insertion_point(field_set_allocated:chunksink.Command.reboot)
}
void Command::set_allocated_cmdcutsession(::chunksink::CmdCutSession* cmdcutsession) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_command();
  if (cmdcutsession) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(cmdcutsession);
    if (message_arena != submessage_arena) {
      cmdcutsession = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, cmdcutsession, submessage_arena);
    }
    set_has_cmdcutsession();
    _impl_.command_.cmdcutsession_ = cmdcutsession;
  }
  // @@protoc_insertion_point(field_set_allocated:chunksink.Command.cmdCutSession)
}
Command::Command(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:chunksink.Command)
}
Command::Command(const Command& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Command* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_command();
  switch (from.command_case()) {
    case kReboot: {
      _this->_internal_mutable_reboot()->::chunksink::Reboot::MergeFrom(
          from._internal_reboot());
      break;
    }
    case kCmdCutSession: {
      _this->_internal_mutable_cmdcutsession()->::chunksink::CmdCutSession::MergeFrom(
          from._internal_cmdcutsession());
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:chunksink.Command)
}

inline void Command::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_command();
}

Command::~Command() {
  // @@protoc_insertion_point(destructor:chunksink.Command)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Command::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_command()) {
    clear_command();
  }
}

void Command::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Command::clear_command() {
// @@protoc_insertion_point(one_of_clear_start:chunksink.Command)
  switch (command_case()) {
    case kReboot: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.command_.reboot_;
      }
      break;
    }
    case kCmdCutSession: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.command_.cmdcutsession_;
      }
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = COMMAND_NOT_SET;
}


void Command::Clear() {
// @@protoc_insertion_point(message_clear_start:chunksink.Command)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_command();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Command::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .chunksink.Reboot reboot = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_reboot(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .chunksink.CmdCutSession cmdCutSession = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_cmdcutsession(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Command::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:chunksink.Command)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .chunksink.Reboot reboot = 1;
  if (_internal_has_reboot()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::reboot(this),
        _Internal::reboot(this).GetCachedSize(), target, stream);
  }

  // .chunksink.CmdCutSession cmdCutSession = 2;
  if (_internal_has_cmdcutsession()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::cmdcutsession(this),
        _Internal::cmdcutsession(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:chunksink.Command)
  return target;
}

size_t Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:chunksink.Command)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (command_case()) {
    // .chunksink.Reboot reboot = 1;
    case kReboot: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.command_.reboot_);
      break;
    }
    // .chunksink.CmdCutSession cmdCutSession = 2;
    case kCmdCutSession: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.command_.cmdcutsession_);
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Command::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Command::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Command::GetClassData() const { return &_class_data_; }


void Command::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Command*>(&to_msg);
  auto& from = static_cast<const Command&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chunksink.Command)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.command_case()) {
    case kReboot: {
      _this->_internal_mutable_reboot()->::chunksink::Reboot::MergeFrom(
          from._internal_reboot());
      break;
    }
    case kCmdCutSession: {
      _this->_internal_mutable_cmdcutsession()->::chunksink::CmdCutSession::MergeFrom(
          from._internal_cmdcutsession());
      break;
    }
    case COMMAND_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Command::CopyFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chunksink.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command::IsInitialized() const {
  return true;
}

void Command::InternalSwap(Command* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.command_, other->_impl_.command_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Command::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chunksink_2eproto_getter, &descriptor_table_chunksink_2eproto_once,
      file_level_metadata_chunksink_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace chunksink
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::chunksink::Chunks*
Arena::CreateMaybeMessage< ::chunksink::Chunks >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chunksink::Chunks >(arena);
}
template<> PROTOBUF_NOINLINE ::chunksink::GetCommandRequest*
Arena::CreateMaybeMessage< ::chunksink::GetCommandRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chunksink::GetCommandRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::chunksink::CmdCutSession*
Arena::CreateMaybeMessage< ::chunksink::CmdCutSession >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chunksink::CmdCutSession >(arena);
}
template<> PROTOBUF_NOINLINE ::chunksink::Reboot*
Arena::CreateMaybeMessage< ::chunksink::Reboot >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chunksink::Reboot >(arena);
}
template<> PROTOBUF_NOINLINE ::chunksink::Command*
Arena::CreateMaybeMessage< ::chunksink::Command >(Arena* arena) {
  return Arena::CreateMessageInternal< ::chunksink::Command >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
