services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: session-recorder-envoy
    ports:
      - "8080:8080"
      - "9901:9901" # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    network_mode: host
