version: "3.3"

services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: session-recorder-envoy
    ports:
      - "8080:8080"
      - "9901:9901" # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    networks:
      - session-recorder-net

networks:
  session-recorder-net:
    external: true
    name: session-recorder_session-recorder-net
